CREATE DATABASE minicraftDB;

-- Подключаемся к созданной базе
\c minicraftDB;

-- Создаем таблицы
CREATE TABLE IF NOT EXISTS Items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(150),
    imageUrl VARCHAR(255), 
    consumable BOOL,
    maxStack INTEGER NOT NULL CHECK (maxStack > 0)
);

CREATE TABLE IF NOT EXISTS Inventory(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    itemId INTEGER NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity >= 0),
    posX INTEGER NOT NULL CHECK (posX >= 0),
    posY INTEGER NOT NULL CHECK (posY >= 0),
    CONSTRAINT fk_inventory_item 
        FOREIGN KEY (itemId) 
        REFERENCES Items(id) 
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT unique_position UNIQUE (posX, posY)
);

CREATE TABLE IF NOT EXISTS Recipes(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    itemId INTEGER NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    duration INTEGER NOT NULL CHECK (duration > 0),
    CONSTRAINT fk_recipe_result 
        FOREIGN KEY (itemId) 
        REFERENCES Items(id) 
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Ingredients(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipeId INTEGER NOT NULL,
    itemId INTEGER NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    posX INTEGER NOT NULL CHECK (posX >= 0),
    posY INTEGER NOT NULL CHECK (posY >= 0),
    CONSTRAINT fk_ingredients_recipe 
        FOREIGN KEY (recipeId) 
        REFERENCES Recipes(id) 
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_ingredients_item 
        FOREIGN KEY (itemId) 
        REFERENCES Items(id) 
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT unique_recipe_position UNIQUE (recipeId, posX, posY)
);
